version: '3.8'

services:
  bot:
    build: .
    container_name: discord-signature-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules 