name: Deploy Discord Bot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            # Installation des dépendances si nécessaire
            if ! command -v docker &> /dev/null; then
              curl -fsSL https://get.docker.com -o get-docker.sh
              sudo sh get-docker.sh
            fi
            
            if ! command -v docker-compose &> /dev/null; then
              sudo curl -L "https://github.com/docker/compose/releases/download/v2.23.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
            fi
            
            # Création et configuration du dossier
            mkdir -p ~/discord-bot
            cd ~/discord-bot
            
            # Configuration de git si c'est la première fois
            if [ ! -d .git ]; then
              git init
              git remote add origin ${{ github.server_url }}/${{ github.repository }}.git
            fi
            
            # Pull du code
            git fetch origin main
            git reset --hard origin/main
            
            # Configuration et démarrage Docker
            echo "DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }}" > .env
            echo "CLIENT_ID=${{ secrets.CLIENT_ID }}" >> .env
            
            # Déploiement des commandes slash
            sudo docker-compose run --rm bot node deploy-commands.js
            
            # Démarrage du bot
            sudo docker-compose down || true
            sudo docker-compose build
            sudo docker-compose up -d 